import { FC } from "react";
import s from "./TokenUtility.module.scss";

const TokenUtility: FC = () => {
  return (
    <div className={s.container}>
      <div className="container">
        <div className="row">
          <div className={`col-md-12 d-flex align-items-center`}>
            <div className={s.content}>
              <h3 className={s.heading}>KOO Utility</h3>
            </div>
          </div>
          <div className="col-md-6">
            <div className={s.contentWrapper}>
              <div className={s.iconWrapper}>
                <img className={s.icon} src="/images/icons/esport.svg" alt="" />
              </div>
              <div className={s.content}>
                <h3 className={`${s.title} ${s.firstSection}`}>
                  E-Sports and Tournaments
                </h3>
                <div className={s.singleContent}>
                  <p>
                    To attract a wide range of players to the KRL ecosystem in
                    the hunt for token rewards and to give ownership and stake
                    to the most active community members, we will reward key
                    behaviors within our ecosystem such as:
                  </p>
                  <ul>
                    <li>Competing in seasons</li>
                    <li>Winning tournaments</li>
                    <li>Using the KRL marketplace</li>
                    <li>Evolving Racers</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div className="col-md-6">
            <div className={s.contentWrapper}>
              <div className={s.iconWrapper}>
                <img
                  className={s.icon}
                  src="/images/icons/staking.svg"
                  alt=""
                />
              </div>
              <div className={s.content}>
                <h3 className={s.title}>Staking</h3>
                <div className={s.singleContent}>
                  <p>
                    Players will be able to lock up their tokens to receive
                    newly created KOO. Stakers will also be required to vote and
                    play to claim rewards.
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div className="col-md-6">
            <div className={s.contentWrapper}>
              <div className={s.iconWrapper}>
                <img
                  className={s.icon}
                  src="/images/icons/payment.svg"
                  alt=""
                />
              </div>
              <div className={s.content}>
                <h3 className={s.title}>Payment</h3>
                <div className={s.singleContent}>
                  <p>
                    KOO will be accepted as currency within the KRL NFT
                    marketplace. KOO may also be used to determine eligibility
                    for participation in certain sales/auctions conducted by the
                    KRL team.
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div className="col-md-6">
            <div className={s.contentWrapper}>
              <div className={s.iconWrapper}>
                <img
                  className={s.icon}
                  src="/images/icons/governance.svg"
                  alt=""
                />
              </div>
              <div className={s.content}>
                <h3 className={s.title}>Governance</h3>
                <div className={s.singleContent}>
                  <p>
                    In early 2022, the Community Treasury will go live and begin
                    to receive revenues generated by KRL as well as a portion of
                    staking rewards. This treasury will be governed by KRL
                    stakers once the network has become sufficiently
                    decentralized.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TokenUtility;
